name: Convert to json

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: YueChan/Live
          path: Live
      - name: convert
        run: |
          ls -lh Live/
          python3 convert.py APTV.m3u
