name: Convert to json

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout Live
        uses: actions/checkout@v4
        with:
          repository: YueChan/Live
          path: Live
      - name: convert
        run: |
          python3 convert.py Live/APTV.m3u
