name: Convert to json

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths: 
      - 'convert.py'
      - '.github/workflows/main.yml'
  schedule:
    - cron: '0 18 * * *'

jobs:
  Convert-to-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout Live
        uses: actions/checkout@v4
        with:
          repository: YueChan/Live
          path: Live
      - name: convert
        run: |
          python3 convert.py Live/APTV.m3u
      - name: Commit and push config.json
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add *.json

          # 检查是否有文件被修改
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          else
            git commit -m "Update json"
            git push
          fi
